### PR TITLE
fixing bad merge

### PR DESCRIPTION
**Pull request by RJP43**
@ebeshero I have moved all of @msb81 's new transcriptions over to the correct folder and removed the bad folder. I think once this is pulled in others can pull from you and all will be well.

### CODE REVIEW

**Review by ebeshero — COMMENTED** [review]
@RJP43 Some of the files being altered are NOT improvements--the schema lines are wrong, for one, and some files are losing `@xml:ids` that we had in place. I think I had better not accept this merge.

**Comment by ebeshero** [comment]
@RJP43 Walk through the files that are being *overwritten* by this merge, and look at the changes--you'll see what I mean.

**Comment by ebeshero** [comment]
@RJP43 I think the only files I should accept are the files that we don't already have in the Montalvo directory...

**Comment by RJP43** [comment]
Well that would be because as @msb81 made those new transcriptions she wasn't aware of the corrected schema lines. Someone closer to the project should reimplement the xml:ids and the schema lines in @msb81 's latest transcriptions.

**Comment by RJP43** [comment]
Ok... my only concern being some of those other edited files are actual transcription corrections, but like I said those closer to the project would know more.

**Comment by msb81** [comment]
The xml id issue has been there since I started the project. I wasn't sure what the issue was, but it never interfered with me writing so I just left it alone.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ebeshero** [comment]
@msb81  @RJP43 I think the problem was that you were adding transcriptions on top of old code. But GitHub was designed for problems like this: We *should* with a little research be able to merge what is new in your files with what is new in mine, but we need to try not to go backwards and lose material. This pull request is going to delete good code we have in place, so I need to figure out how not to let it do that. 

@RJP43 We may need a new pull request that comes after a fetch and merge? Can you help me research this? It is easy to see what we are about to lose by letting this pull request overwrite the files in the Montalvo directory. It would be harder and more tedious to correct the files one by one if I pull this in.

**Comment by ebeshero** [comment]
@RJP43 What I noticed right away are schema line changes, but there may be more--contributions from others in the bodies of the files. I think we need to be merging these directories together rather than replacing one with the other, and we may actually want to *invite* git's merge conflict markup in the files to help us catch everything those of us inside the project need to repair by hand.

**Comment by RJP43** [comment]
Ok... I haven't got out my computer yet but just thinking thru this as I'm waking up here .... deny my pull request... I will reset my head to the main repo. Then to get the files to merge together without much by hand work ... create a branch where you do the work of moving ALL of @msb81 files (even the problematic ones because they seem to have new bits) into the correct folder even replacing the old files with same name. Then when you switch back to master and try to merge the new branch in you will either merge files because not editing same spots or get the markup inside each troublesome file. I think that's the best way... @ebeshero thoughts?

**Comment by ebeshero** [comment]
@RJP43 Yes, I think that makes sense--We'd be asking Git to perform a merge of two branches that way. Apparently the Pull request wasn't going to do that merging on its own, which is interesting!

**Comment by RJP43** [comment]
@ebeshero Here is where this conversation left off.

**Comment by RJP43** [comment]
@ebeshero I still think your best bet is moving all of the files from Maddie's Montalvo folder to the correct folder on a separate branch and then go forward with trying to merge the branches allowing git to merge the changes together.

**Comment by ebeshero** [comment]
@RJP43 Good-- yes, that's what I remember too! I think I set this aside for a quiet moment (like now) to figure it out! I'll make an experimental branch to try the merge.

**Comment by RJP43** [comment]
@ebeshero Ok keep me posted. I am going to work on Project remarks.

**Pull request closed without merging**
