### PR TITLE
Increased accuracy on the translations and alternative TOC

### PR DESCRIPTION
**Pull request by HelenaSabel**
In these commits:
- I added `<seg>` elements to Montalvo with an ID whenever there was a transposition in Southey, that is, when Southey translated a part of one clause, then a different clause, and later retrieved partial contents of that first clause (you can view here an example in the 6th and 8th row: http://amadis.newtfire.org/Chapter1.html ). With the new markup the results are:
   because her husband // porque el Rey su marido |
   taking great pleasure to behold her beautiful tresses, // tanto era pagado de los ver.  |
   would have them covered only with a chaplet of flowers. // nunca la consintió cubrir sus hermosos cabellos sino de una muy rica guirnalda/
- I modified the transformations accordingly to create the new FS files and the new HTML tables.
- I created a different table of contents (toc-2.html). As @ebeshero suggested before, I gave Montalvo a fixed width. I also eliminated the word count statistics because those could be more useful in a particular analysis of the work than in the table of contents.

### CODE REVIEW

**Comment by ebeshero** [comment]
@setriplette @HelenaSabel I've just merged the pull request, but Stacey you'll want to look at this as a new level of coding related to our "stitchery" work and the comparison files. I'll need to go post these on the website, too. 

For now, one neat trick with GitHub that I've just learned is that you can see an HTML file we post here in a GitHub preview mode by putting this string ahead of our file URL on GitHub: http://htmlpreview.github.io/?

So, to view Helena's alterations to Chapter 1 in the web browser, see:
http://htmlpreview.github.io/?https://github.com/ebeshero/Amadis-in-Translation/blob/master/html/Chapter1.html
by contrast with our original view posted on the site: http://amadis.newtfire.org/Chapter1.html

**Comment by HelenaSabel** [comment]
That's a very cool trick I didn't know about. Thank you @ebeshero!

There is a rule in our Schematron now that forbids the use of two <anchor> elements with the same ID. So whenever the need arises to “repeat” the identification of a clause, we'll be suggested to go to Montalvo's file and divide the clause so as to create as many segmentations as needed. For example, in Montalvo's first chapter I only had to segment nine of the 225 clauses (so it's not that common).

**Comment by HelenaSabel** [comment]
So do you like the new TOC? http://htmlpreview.github.io/?https://github.com/ebeshero/Amadis-in-Translation/blob/master/html/toc-2.html

**Comment by ebeshero** [comment]
@HelenaSabel Hmmm. About the Schematron: Let me make sure I understand this clearly from the top, so It's clear to @setriplette too. 
- The point of using @xml:ids at all is simply to distinguish each Montalvo "clause-like chunk" from the others. And of course, we've already generated many, many @xml:ids that we're already referencing in the Southey files, so we don't want to change any existing chunks.
- We need to segment or subdivide just a few of these, because Southey is breaking some Montalvo  chunks into pieces and separating them, and our tables can't easily show what's happening when Southey does this sort of patchwork. 
- So, when it comes up, Helena is going back to Montalvo and adding `<seg>` elements inside the relevant clause chunks. And, if I understand you correctly, you are adding new @xml:ids to these seg elements, right? And (because I accepted that merge request on my way to class earlier today) I haven't actually looked for the new seg elements in the Montalvo code yet...Can you highlight an example with a line-comment here? Stacey and I will meet tomorrow afternoon for a long Amadis chat so I can fill her in on this stuff, and I want to make sure I'm clear on it!

**Comment by ebeshero** [comment]
@HelenaSabel Now, as for the table of contents, I agree it makes sense to move the word count comparisons elsewhere, probably to the chapter tables(?) The Venn strip is cool, but I want to make sure it's really proportional, and I still think I'd be more comfortable with two separate rectangles, one representing the total of Montalvo and how much of Montalvo actually appears in Southey, and one based on the total of Southey and how much of _his_ text isn't in Montalvo. The totality of the block could be turned into percentage values, or scaled by a factor that resolves their different word-count proportions, but I worry that we're really working with two different sets of totals here but we're projecting a visual illusion of one single total. And it looks appealing, but isn't very easy to explain what we're representing or why we present it as if it were a singular whole.

If I tried generating a single block like that, I think I'd want to base its total on the word count of Southey + the word count of Montalvo. And then the block in the middle would quite literally represent the percentage of words that appear to correspond across both texts...next to the percent that appear to be distinct in only one or the other.  I think that's not how we're currently merging those bars, is it? 

Small stuff: Can we try putting the bars to the right of the text identifying the chapters? So, chapter list on the left with corresponding bars on the right?

What if we removed the solid black border around the bars?

Thanks for working on this and all the good thinking you've been applying to it!

**Comment by HelenaSabel** [comment]
Hello! 
I understand your misgivings about the overlapping bars. 
They are two individual bars (one calculated with Montalvo's data and the other one with Southey's) that overlapped. Even when giving a fixed width to the Montalvo one, Southey's length change because I do keep the proportions. I positioned Southey's bar by calculating the portion of Montalvo's text not present in his translation.
However, I'm not using word counts for these, but the number of matching clauses instead. I thought the data would be more “neutral”, more related to the translation than to the particularities of each language. Was I wrong on my assumption? If we were to calculate the length of the bars using the word counts (instead of the clauses/anchor counts), Southey's bar would be much more smaller than Montalvo and his additions would be insignificant (because, so far, those are usually one/two words long). It would give you a better idea of Southey's shrinking process, but we might loose the perspective of how much of Montalvo's content is present somehow in Southey and how much is completed omitted (and I think the way to grasp that information is by using the clauses/anchors as the base for the calculations). 
How about I make more graphs (using word counts, clause counts, information of the percentages and so on) and by seeing them together we are able to decide which type suits us better?

**Comment by ebeshero** [comment]
@HelenaSabel Okay--that is a helpful explanation, and I see how working from word counts will likely look a lot different. When you ask if you were wrong in your attempt to present the changes in a more "neutral" way, the need to use those quotation marks is a pretty good signal of what's worrying me. We are finding that we need to represent data in the same graph based on two different proportional scales. I incorrectly presumed just now that this was based on word count, but you remind me it was a count of clauses. Okay. But we still have a problem of one portion of your graph being based on a total count of clauses in Montalvo, and another based on the total count of clauses in Southey, right?

1) Can the problem be resolved, I wonder, by calculating all three bars (omissions, matches, deletions) based simply on the total number of clauses in Montalvo (TM) plus the total number of clauses in Southey (TS)? Then each bar would reflect a portion of a larger combined total, and I think we might be able to resolve the misproportion issue in the current plot.

2) Alternatively, we could simply plot the Montalvo-based calculation in a separate bar from the Southey-based calculation.

3)  We could probably plot both 1) and 2) and that might be worth reviewing together!

I do, definitely, want us to go back and think carefully about explaining exactly the basis of our plots, and that explanation really needs to be present on the HTML we post to our website.
I likely just forgot something I knew two months ago about those plots, that they are based on numbers of matching clauses and not word counts, but since this is complicated and we are all busy, and we need to be able to communicate clearly with each other and others interested in our project, we really need some clear explanation of the basis of our calculations to be posted for all to see. I am happy to help with that.

**Pull request merged**
